services:
  ifheroesbot:
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
    build:
      args:
      - token=
      - clientId=
      - guildId=
      - roleId=
      - color=fff
      - api_url=https://api.ifheroes.de/v1/news
      - botAdminRole=
      - mongodbURI=mongodb://
    ports:
    - "8080:8080"

    volumes:
      - ./exports:/bot/exports
